# Numpy

## One-Dimensional Array

In [ ]:
import numpy as np


## Two-Dimensional Array

In [20]:
import numpy as np
from IPython.display import display
sample_matrix = np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [21]:
sample_matrix[2][3]

7

In [22]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [24]:
sample_matrix[2]

array([56, 76, 24,  7])

In [23]:
sample_matrix[1][3]

33

In [26]:
sample_matrix[0:2,2]

array([ 1, 21])

In [32]:
import numpy as np
sample_array = np.arange(1, 20)
display(sample_array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [33]:
array = np.random.randn(3,4)
display(array)

array([[-0.18053252,  0.58573802, -1.76134642, -0.73019431],
       [-0.42412477,  0.57375915,  0.92790196,  1.33321832],
       [-0.80223551,  1.36519326,  0.9156317 , -1.05616593]])