# Numpy

## One-Dimensional Array

In [1]:
import numpy as np


## Two-Dimensional Array

In [2]:
import numpy as np
from IPython.display import display
sample_matrix = np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [3]:
sample_matrix[2][3]

7

In [4]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [5]:
sample_matrix[2]

array([56, 76, 24,  7])

In [6]:
sample_matrix[1][3]

33

In [7]:
sample_matrix[0:2,2]

array([ 1, 21])

In [8]:
import numpy as np
sample_array = np.arange(1, 20)
display(sample_array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
array = np.random.randn(3,4)
display(array)

array([[-1.10040617,  0.48943529, -0.05015002,  0.40524571],
       [ 2.29214049,  0.62833079,  0.07149699, -1.26898668],
       [ 0.11859982,  0.30484786,  1.31430227, -0.36947381]])