# Numpy

## One-Dimensional Array

In [1]:
import numpy as np


## Two-Dimensional Array

In [2]:
import numpy as np
from IPython.display import display
sample_matrix = np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [3]:
sample_matrix[2][3]

7

In [4]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [5]:
sample_matrix[2]

array([56, 76, 24,  7])

In [6]:
sample_matrix[1][3]

33

In [7]:
sample_matrix[0:2,2]

array([ 1, 21])

In [8]:
import numpy as np
sample_array = np.arange(1, 20)
display(sample_array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
array = np.random.randn(3,4)
display(array)

array([[-0.05661463, -0.0255375 , -0.65076369, -2.3369381 ],
       [-0.16160697, -0.06384219,  0.46982451,  0.29509372],
       [-0.41849978, -1.20929704,  0.95158631,  1.4129183 ]])